# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import image_rc

class Ui_Main(object):
    def setupUi(self, Main):
        if not Main.objectName():
            Main.setObjectName(u"Main")
        Main.resize(1024, 576)
        self.actionNew = QAction(Main)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/image/img/new.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(Main)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u":/image/img/open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(Main)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/image/img/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave_as = QAction(Main)
        self.actionSave_as.setObjectName(u"actionSave_as")
        icon3 = QIcon()
        icon3.addFile(u":/image/img/saveas.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave_as.setIcon(icon3)
        self.actionPrint = QAction(Main)
        self.actionPrint.setObjectName(u"actionPrint")
        icon4 = QIcon()
        icon4.addFile(u":/image/img/print.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint_preview = QAction(Main)
        self.actionPrint_preview.setObjectName(u"actionPrint_preview")
        icon5 = QIcon()
        icon5.addFile(u":/image/img/printprev.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPrint_preview.setIcon(icon5)
        self.actionExit = QAction(Main)
        self.actionExit.setObjectName(u"actionExit")
        icon6 = QIcon()
        icon6.addFile(u":/image/img/exit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionCopy = QAction(Main)
        self.actionCopy.setObjectName(u"actionCopy")
        icon7 = QIcon()
        icon7.addFile(u":/image/img/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon7)
        self.actionCut = QAction(Main)
        self.actionCut.setObjectName(u"actionCut")
        icon8 = QIcon()
        icon8.addFile(u":/image/img/cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon8)
        self.actionPaste = QAction(Main)
        self.actionPaste.setObjectName(u"actionPaste")
        icon9 = QIcon()
        icon9.addFile(u":/image/img/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon9)
        self.actionUndo = QAction(Main)
        self.actionUndo.setObjectName(u"actionUndo")
        icon10 = QIcon()
        icon10.addFile(u":/image/img/undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon10)
        self.actionRedo = QAction(Main)
        self.actionRedo.setObjectName(u"actionRedo")
        icon11 = QIcon()
        icon11.addFile(u":/image/img/redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon11)
        self.actionFont = QAction(Main)
        self.actionFont.setObjectName(u"actionFont")
        icon12 = QIcon()
        icon12.addFile(u":/image/img/font.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFont.setIcon(icon12)
        self.actionColor = QAction(Main)
        self.actionColor.setObjectName(u"actionColor")
        icon13 = QIcon()
        icon13.addFile(u":/image/img/color.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionColor.setIcon(icon13)
        self.actionBold = QAction(Main)
        self.actionBold.setObjectName(u"actionBold")
        icon14 = QIcon()
        icon14.addFile(u":/image/img/bold.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBold.setIcon(icon14)
        self.actionItalic = QAction(Main)
        self.actionItalic.setObjectName(u"actionItalic")
        icon15 = QIcon()
        icon15.addFile(u":/image/img/italic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionItalic.setIcon(icon15)
        self.actionUnderline = QAction(Main)
        self.actionUnderline.setObjectName(u"actionUnderline")
        icon16 = QIcon()
        icon16.addFile(u":/image/img/underline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUnderline.setIcon(icon16)
        self.actionAbout = QAction(Main)
        self.actionAbout.setObjectName(u"actionAbout")
        icon17 = QIcon()
        icon17.addFile(u":/image/img/about.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout.setIcon(icon17)
        self.actionAbout_Qt_lisence = QAction(Main)
        self.actionAbout_Qt_lisence.setObjectName(u"actionAbout_Qt_lisence")
        icon18 = QIcon()
        icon18.addFile(u":/image/img/aboutqt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAbout_Qt_lisence.setIcon(icon18)
        self.actionKey_Time_Line = QAction(Main)
        self.actionKey_Time_Line.setObjectName(u"actionKey_Time_Line")
        self.actionTime = QAction(Main)
        self.actionTime.setObjectName(u"actionTime")
        self.actionSide_Notes = QAction(Main)
        self.actionSide_Notes.setObjectName(u"actionSide_Notes")
        self.actionYour_Account = QAction(Main)
        self.actionYour_Account.setObjectName(u"actionYour_Account")
        self.actionEdit_your_information = QAction(Main)
        self.actionEdit_your_information.setObjectName(u"actionEdit_your_information")
        self.actionWord_Count = QAction(Main)
        self.actionWord_Count.setObjectName(u"actionWord_Count")
        self.centralwidget = QWidget(Main)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.Left_widget = QWidget(self.splitter)
        self.Left_widget.setObjectName(u"Left_widget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_widget.sizePolicy().hasHeightForWidth())
        self.Left_widget.setSizePolicy(sizePolicy)
        self.Left_widget.setMinimumSize(QSize(200, 0))
        self.Left_widget.setMaximumSize(QSize(200, 16777215))
        self.Left_widget.setBaseSize(QSize(0, 0))
        self.Left_widget.setStyleSheet(u"QWidget#Left_widget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"}")
        self.verticalLayout = QVBoxLayout(self.Left_widget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.Left_widget)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(16777215, 28))
        font = QFont()
        font.setFamily(u"Roboto Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.TimeList = QListWidget(self.Left_widget)
        QListWidgetItem(self.TimeList)
        QListWidgetItem(self.TimeList)
        QListWidgetItem(self.TimeList)
        self.TimeList.setObjectName(u"TimeList")
        sizePolicy.setHeightForWidth(self.TimeList.sizePolicy().hasHeightForWidth())
        self.TimeList.setSizePolicy(sizePolicy)
        self.TimeList.setDragEnabled(False)
        self.TimeList.setDragDropMode(QAbstractItemView.DragDrop)
        self.TimeList.setDefaultDropAction(Qt.MoveAction)

        self.verticalLayout.addWidget(self.TimeList)

        self.time_line_btn_frame = QFrame(self.Left_widget)
        self.time_line_btn_frame.setObjectName(u"time_line_btn_frame")
        self.time_line_btn_frame.setMaximumSize(QSize(16777215, 28))
        self.time_line_btn_frame.setFrameShape(QFrame.StyledPanel)
        self.time_line_btn_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.time_line_btn_frame)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.btn_plus = QPushButton(self.time_line_btn_frame)
        self.btn_plus.setObjectName(u"btn_plus")
        self.btn_plus.setMinimumSize(QSize(16, 16))
        self.btn_plus.setMaximumSize(QSize(17, 17))
        font1 = QFont()
        font1.setFamily(u"Roboto Light")
        font1.setPointSize(25)
        self.btn_plus.setFont(font1)
        self.btn_plus.setStyleSheet(u"QPushButton {\n"
"	border: none;\n"
"	border-radius: 8px;	\n"
"	background-color: rgb(149, 165, 166);\n"
"}\n"
"QPushButton:hover {	\n"
"	background-color: rgba(149, 165, 166, 150);\n"
"}")

        self.horizontalLayout_3.addWidget(self.btn_plus)

        self.btn_minus = QPushButton(self.time_line_btn_frame)
        self.btn_minus.setObjectName(u"btn_minus")
        self.btn_minus.setMinimumSize(QSize(16, 16))
        self.btn_minus.setMaximumSize(QSize(17, 17))
        font2 = QFont()
        font2.setFamily(u"Roboto Light")
        font2.setPointSize(30)
        self.btn_minus.setFont(font2)
        self.btn_minus.setStyleSheet(u"QPushButton {\n"
"	border: none;\n"
"	border-radius: 8px;	\n"
"	background-color: rgb(149, 165, 166);\n"
"}\n"
"QPushButton:hover {	\n"
"	background-color: rgba(149, 165, 166, 150);\n"
"}")

        self.horizontalLayout_3.addWidget(self.btn_minus)


        self.verticalLayout.addWidget(self.time_line_btn_frame)

        self.splitter.addWidget(self.Left_widget)
        self.Center_widget = QWidget(self.splitter)
        self.Center_widget.setObjectName(u"Center_widget")
        self.Center_widget.setStyleSheet(u"background-color: rgb(178, 190, 195);")
        self.horizontalLayout_2 = QHBoxLayout(self.Center_widget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(20, 20, 20, 20)
        self.textEdit_Script = QTextEdit(self.Center_widget)
        self.textEdit_Script.setObjectName(u"textEdit_Script")
        self.textEdit_Script.setStyleSheet(u"background-color: rgb(255, 255, 255);")

        self.horizontalLayout_2.addWidget(self.textEdit_Script)

        self.splitter.addWidget(self.Center_widget)
        self.Right_widget = QWidget(self.splitter)
        self.Right_widget.setObjectName(u"Right_widget")
        sizePolicy.setHeightForWidth(self.Right_widget.sizePolicy().hasHeightForWidth())
        self.Right_widget.setSizePolicy(sizePolicy)
        self.Right_widget.setMinimumSize(QSize(200, 0))
        self.Right_widget.setMaximumSize(QSize(200, 16777215))
        self.Right_widget.setStyleSheet(u"QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"}")
        self.verticalLayout_2 = QVBoxLayout(self.Right_widget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.time = QFrame(self.Right_widget)
        self.time.setObjectName(u"time")
        self.time.setMinimumSize(QSize(0, 100))
        self.time.setMaximumSize(QSize(16777215, 100))
        self.time.setStyleSheet(u"")
        self.time.setFrameShape(QFrame.StyledPanel)
        self.time.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.time)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.time)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(16777215, 28))
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setStyleSheet(u"border: none;\n"
"border-bottom: 1px solid;")
        self.label_2.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.label_2)

        self.current_time_label = QLabel(self.time)
        self.current_time_label.setObjectName(u"current_time_label")
        font3 = QFont()
        font3.setFamily(u"Roboto Light")
        font3.setPointSize(24)
        self.current_time_label.setFont(font3)
        self.current_time_label.setStyleSheet(u"border: none;")
        self.current_time_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_4.addWidget(self.current_time_label)


        self.verticalLayout_2.addWidget(self.time)

        self.word_count = QFrame(self.Right_widget)
        self.word_count.setObjectName(u"word_count")
        self.word_count.setMinimumSize(QSize(0, 100))
        self.word_count.setMaximumSize(QSize(16777215, 100))
        self.word_count.setStyleSheet(u"")
        self.word_count.setFrameShape(QFrame.StyledPanel)
        self.word_count.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.word_count)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.word_count)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMaximumSize(QSize(16777215, 28))
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(Qt.LeftToRight)
        self.label_5.setStyleSheet(u"border: none;\n"
"border-bottom: 1px solid;")
        self.label_5.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.label_5)

        self.word_count_label = QLabel(self.word_count)
        self.word_count_label.setObjectName(u"word_count_label")
        font4 = QFont()
        font4.setFamily(u"Roboto Light")
        font4.setPointSize(15)
        self.word_count_label.setFont(font4)
        self.word_count_label.setStyleSheet(u"border: none;")
        self.word_count_label.setAlignment(Qt.AlignCenter)

        self.verticalLayout_5.addWidget(self.word_count_label)


        self.verticalLayout_2.addWidget(self.word_count)

        self.sidenotes = QFrame(self.Right_widget)
        self.sidenotes.setObjectName(u"sidenotes")
        self.sidenotes.setStyleSheet(u"")
        self.sidenotes.setFrameShape(QFrame.StyledPanel)
        self.sidenotes.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.sidenotes)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.sidenotes)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMaximumSize(QSize(16777215, 28))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"border: none;\n"
"border-bottom: 1px solid;")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.label_4)

        self.textEdit_Sidenotes = QTextEdit(self.sidenotes)
        self.textEdit_Sidenotes.setObjectName(u"textEdit_Sidenotes")
        self.textEdit_Sidenotes.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border: none;")

        self.verticalLayout_3.addWidget(self.textEdit_Sidenotes)


        self.verticalLayout_2.addWidget(self.sidenotes)

        self.splitter.addWidget(self.Right_widget)

        self.horizontalLayout.addWidget(self.splitter)

        Main.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Main)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFormat = QMenu(self.menubar)
        self.menuFormat.setObjectName(u"menuFormat")
        self.menuStyle = QMenu(self.menubar)
        self.menuStyle.setObjectName(u"menuStyle")
        self.menuShow = QMenu(self.menubar)
        self.menuShow.setObjectName(u"menuShow")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuTeleprompter = QMenu(self.menubar)
        self.menuTeleprompter.setObjectName(u"menuTeleprompter")
        self.menuAccount = QMenu(self.menubar)
        self.menuAccount.setObjectName(u"menuAccount")
        Main.setMenuBar(self.menubar)
        self.toolBar = QToolBar(Main)
        self.toolBar.setObjectName(u"toolBar")
        Main.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuStyle.menuAction())
        self.menubar.addAction(self.menuShow.menuAction())
        self.menubar.addAction(self.menuTeleprompter.menuAction())
        self.menubar.addAction(self.menuAccount.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionPrint_preview)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addAction(self.actionColor)
        self.menuStyle.addAction(self.actionBold)
        self.menuStyle.addAction(self.actionItalic)
        self.menuStyle.addAction(self.actionUnderline)
        self.menuShow.addAction(self.actionKey_Time_Line)
        self.menuShow.addAction(self.actionTime)
        self.menuShow.addAction(self.actionWord_Count)
        self.menuShow.addAction(self.actionSide_Notes)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionAbout_Qt_lisence)
        self.menuAccount.addAction(self.actionYour_Account)
        self.menuAccount.addSeparator()
        self.menuAccount.addAction(self.actionEdit_your_information)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionUndo)
        self.toolBar.addAction(self.actionRedo)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalic)
        self.toolBar.addAction(self.actionUnderline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionFont)
        self.toolBar.addAction(self.actionColor)

        self.retranslateUi(Main)

        QMetaObject.connectSlotsByName(Main)
    # setupUi

    def retranslateUi(self, Main):
        Main.setWindowTitle(QCoreApplication.translate("Main", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("Main", u"New", None))
        self.actionOpen.setText(QCoreApplication.translate("Main", u"Open...", None))
        self.actionSave.setText(QCoreApplication.translate("Main", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("Main", u"Save as...", None))
        self.actionPrint.setText(QCoreApplication.translate("Main", u"Print", None))
        self.actionPrint_preview.setText(QCoreApplication.translate("Main", u"Print Preview", None))
        self.actionExit.setText(QCoreApplication.translate("Main", u"Exit", None))
        self.actionCopy.setText(QCoreApplication.translate("Main", u"Copy", None))
        self.actionCut.setText(QCoreApplication.translate("Main", u"Cut", None))
        self.actionPaste.setText(QCoreApplication.translate("Main", u"Paste", None))
        self.actionUndo.setText(QCoreApplication.translate("Main", u"Undo", None))
        self.actionRedo.setText(QCoreApplication.translate("Main", u"Redo", None))
        self.actionFont.setText(QCoreApplication.translate("Main", u"Font", None))
        self.actionColor.setText(QCoreApplication.translate("Main", u"Color", None))
        self.actionBold.setText(QCoreApplication.translate("Main", u"Bold", None))
        self.actionItalic.setText(QCoreApplication.translate("Main", u"Italic", None))
        self.actionUnderline.setText(QCoreApplication.translate("Main", u"Underline", None))
        self.actionAbout.setText(QCoreApplication.translate("Main", u"About", None))
        self.actionAbout_Qt_lisence.setText(QCoreApplication.translate("Main", u"About Qt lisence", None))
        self.actionKey_Time_Line.setText(QCoreApplication.translate("Main", u"Key Time Line", None))
        self.actionTime.setText(QCoreApplication.translate("Main", u"Current Time", None))
        self.actionSide_Notes.setText(QCoreApplication.translate("Main", u"Side Notes", None))
        self.actionYour_Account.setText(QCoreApplication.translate("Main", u"Your Account", None))
        self.actionEdit_your_information.setText(QCoreApplication.translate("Main", u"Logout", None))
        self.actionWord_Count.setText(QCoreApplication.translate("Main", u"Word Count", None))
        self.label.setText(QCoreApplication.translate("Main", u"Key Time Line", None))

        __sortingEnabled = self.TimeList.isSortingEnabled()
        self.TimeList.setSortingEnabled(False)
        ___qlistwidgetitem = self.TimeList.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("Main", u"TimeLine1", None));
        ___qlistwidgetitem1 = self.TimeList.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("Main", u"TimeLine2", None));
        ___qlistwidgetitem2 = self.TimeList.item(2)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("Main", u"TimeLine3", None));
        self.TimeList.setSortingEnabled(__sortingEnabled)

#if QT_CONFIG(tooltip)
        self.btn_plus.setToolTip(QCoreApplication.translate("Main", u"Maximize", None))
#endif // QT_CONFIG(tooltip)
        self.btn_plus.setText(QCoreApplication.translate("Main", u"+", None))
#if QT_CONFIG(tooltip)
        self.btn_minus.setToolTip(QCoreApplication.translate("Main", u"Maximize", None))
#endif // QT_CONFIG(tooltip)
        self.btn_minus.setText(QCoreApplication.translate("Main", u"-", None))
        self.textEdit_Script.setHtml(QCoreApplication.translate("Main", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"># Text goes here</p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("Main", u"Current Time", None))
        self.current_time_label.setText(QCoreApplication.translate("Main", u"12:34", None))
        self.label_5.setText(QCoreApplication.translate("Main", u"Word Count", None))
        self.word_count_label.setText(QCoreApplication.translate("Main", u"1234 words to 56:78", None))
        self.label_4.setText(QCoreApplication.translate("Main", u"Side Notes", None))
        self.textEdit_Sidenotes.setHtml(QCoreApplication.translate("Main", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"># Text goes here</p></body></html>", None))
        self.menuFile.setTitle(QCoreApplication.translate("Main", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("Main", u"Edit", None))
        self.menuFormat.setTitle(QCoreApplication.translate("Main", u"Format", None))
        self.menuStyle.setTitle(QCoreApplication.translate("Main", u"Style", None))
        self.menuShow.setTitle(QCoreApplication.translate("Main", u"Show", None))
        self.menuAbout.setTitle(QCoreApplication.translate("Main", u"About", None))
        self.menuTeleprompter.setTitle(QCoreApplication.translate("Main", u"Teleprompter", None))
        self.menuAccount.setTitle(QCoreApplication.translate("Main", u"Setting", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("Main", u"toolBar", None))
    # retranslateUi

